language: php

sudo: false

php:
  - 5.4

before_script:
  - composer self-update

install:
  - composer install --prefer-source
  - composer require --dev squizlabs/php_codesniffer
  - composer require --dev sebastianbergmann/phploc
  - composer require --dev sebastianbergmann/phpcpd
  - composer require --dev phpmd/phpmd

script:
  - phpunit --stderr --configuration phpunit.xml
  - vendor/bin/phpcs --standard=psr2 app/
  - vendor/bin/phpcpd --verbose app/
  - vendor/bin/phpmd app/ text codesize,unusedcode,naming,design
  - vendor/bin/phploc app/