language: php

sudo: false

php:
  - 5.5

services:
  - mysql

env:
  - VCAP_SERVICES="{'cleardb':[{'credentials':{'username':'root','name':'tpms','hostname':'127.0.0.1','password':''}}]}"

before_install:
  - composer self-update

install:
  - composer install --prefer-source
  - composer require --dev squizlabs/php_codesniffer
  - composer require --dev phploc/phploc
  - composer require --dev sebastian/phpcpd
  - composer require --dev phpmd/phpmd

before_script:
  - mysql -e 'create database tpms;'
  - php artisan migrate:refresh --seed --force

script:
  - phpunit --stderr --configuration phpunit.xml
  - vendor/bin/phpcs --standard=psr2 app/
  - vendor/bin/phpcpd --verbose app/
  - vendor/bin/phpmd app/ text codesize,unusedcode,naming,design
  - vendor/bin/phploc app/

notifications:
  email:
    recipients:
      - felipe@alientronics.com.br
      - henrique.dias@alientronics.com.br
    on_success: change
    on_failure: always